# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phasedb < Formula
  desc "Expand-contract migration coordinator"
  homepage "https://github.com/ddevilz/phasedb"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddevilz/phasedb/releases/download/v0.1.0/phasedb_0.1.0_darwin_amd64.tar.gz"
      sha256 "73668cee0ae7d0fe46fa03a33bcff273b1b1c75ae8bffb80801497e2e6398967"

      define_method(:install) do
        bin.install "phasedb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddevilz/phasedb/releases/download/v0.1.0/phasedb_0.1.0_darwin_arm64.tar.gz"
      sha256 "635efa5eec2ee7289a218c784a7cda28efe9239653c2f781007f7cc774ae4aec"

      define_method(:install) do
        bin.install "phasedb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddevilz/phasedb/releases/download/v0.1.0/phasedb_0.1.0_linux_amd64.tar.gz"
      sha256 "d1c85af945156e6d4e08796a248f6d5195e0090f3a3f053d479e6e44e1cef76f"
      define_method(:install) do
        bin.install "phasedb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddevilz/phasedb/releases/download/v0.1.0/phasedb_0.1.0_linux_arm64.tar.gz"
      sha256 "2fb8ae4fe2672eaaa17d32e7290e031a106fb4885e30f5ab8c55fc705403883e"
      define_method(:install) do
        bin.install "phasedb"
      end
    end
  end
end
